# Generated by Django 6.1.2 on 2026-10-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_producto_marca"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="creado_en",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="marca",
        ),
    ]
