# Generated by Django 6.1.2 on 2026-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
